docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Usage: usage.md
site_name: laminas-i18n-resources
site_description: laminas-i18n-resources
repo_url: 'https://github.com/laminas/laminas-i18n-resources'
